services:
  productservice.api:
    image: productservice
    build:
      context: .
      dockerfile: ProductService.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMQ__HostName=store-rabbitmq
      - RabbitMQ__QueueName=productservice-queue
      - RabbitMQ__Port=5672
    volumes:
      - productservice-data:/app/Data
    depends_on:
      - rabbitmq
    networks:
      - shared-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/app/Data
    environment:
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    networks:
      - shared-network

volumes:
  productservice-data:
  rabbitmq-data:

networks:
  shared-network:
    external: true
