services:
  productservice.api:
    image: productservice.api:latest
    build:
      context: .
      dockerfile: ProductService.Api/Dockerfile
    ports:
      - "${PRODUCTSERVICE_PORT}:${PRODUCTSERVICE_PORT}"
      - "8081:8081"
    env_file:
      - ../.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - productservice-data:/app/Data
    networks:
      - shared-network
    depends_on:
      - store-mq

  store-mq:
    image: rabbitmq:3-management
    container_name: ${RABBITMQ__QUEUENAME}
    hostname: ${RABBITMQ__HOSTNAME}
    ports:
      - "${RABBITMQ__PORT}:${RABBITMQ__PORT}"
      - "15672:15672"
    env_file:
      - ../.env
    volumes:
      - rabbitmq-data:/app/Data
    networks:
      - shared-network

volumes:
  productservice-data:
  rabbitmq-data:

networks:
  shared-network:
    external: true
