services:
  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ProductService.Api/Dockerfile
    ports:
      - "${PRODUCTSERVICE_PORT}:${PRODUCTSERVICE_PORT}"
      - "${PRODUCTSERVICE_PORTALT}:${PRODUCTSERVICE_PORTALT}"
    env_file:
      - ../.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - productservice-data:/app/Data
    networks:
      - shared-network
    depends_on:
      - store-mq

  store-mq:
    image: rabbitmq:3-management
    container_name: ${RABBITMQ__QUEUENAME}
    hostname: ${RABBITMQ__HOSTNAME}
    ports:
      - "${RABBITMQ__PORT}:${RABBITMQ__PORT}"
      - "${RABBITMQ__PORTALT}:${RABBITMQ__PORTALT}"
    env_file:
      - ../.env
    volumes:
      - store-mq-data:/app/Data
    networks:
      - shared-network

volumes:
  productservice-data:
  store-mq-data:

networks:
  shared-network:
    external: true
